# input
data_path: "../../dataset/af_project_dataset/AF-reference_datasets190511/genome-std-assembled-fish_mito/dataset/assembled-fish_mito"

# output
output_path: "../../result/assembled-fish_mito"

# methods
k_mers_method: "start_ry_matches"
background_matches_method: "no_background_matches"
bool_use_single_seq: false # true
bool_use_empirical_formula: true

