# input
data_path: "../dataset/test.fasta"

# reproduction figure
show_all_F_k: True

# available subseq methods
subseq_methods: ["basic_kmer_matches", "spaced_word_matches", "start_ry_matches"]
single_seq: True

# output
figure_output_path: "../result/figure/"