# input
data_path: "../dataset/test.fasta"

# output
output_path: "../result"

# parameters
k_show_values: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

test method:
  k_mers_method: "start_ry_matches"
  background_matches_method: "no_background_matches"
  bool_use_single_seq: true
  bool_use_empirical_formula: true

control method:
  k_mers_method: "basic_kmer_matches"
  background_matches_method: "no_background_matches"
  bool_use_single_seq: true
  bool_use_empirical_formula: true

